pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./hm5_quickstart_importing.htm","Welcome to Help+Manual! &#62; Importing data","You can import existing documentation into your Help+Manual projects from a wide variety of different formats. When you import data you can either...",""],
["./hm_quickstart.htm","Welcome to Help+Manual!","Local, local, all the problems of the world are local. The next paragraph remains unchanged. provide a quick introduction to using Help+Manual. Th...",""],
["./hm_quickstart_addtopics.htm","Welcome to Help+Manual! &#62; Adding topics","The New Project option creates some topics for you automatically but normally you will create topics yourself. Creating a topic in Help+Manual is ...",""],
["./hm_quickstart_compile.htm","Welcome to Help+Manual! &#62; Publishing your project","Once you have completed a couple of topics you will want to publish your output to see what your finished product is going to look like. You can o...",""],
["./hm_quickstart_edittopics.htm","Welcome to Help+Manual! &#62; Editing topics","local local Entering and editing text in your topics in Help+Manual is very similar to working in a word processor. To edit a topic select the top...",""],
["./hm_quickstart_explorer.htm","Using the Project Explorer","The Project Explorer is the control center for your Help+Manual projects. It displays the structure of your project with the Table of Contents (TO...",""],
["./hm_quickstart_explorer_navigate.htm","Using the Project Explorer &#62; Navigating in the Project Explorer","If you are familiar with Windows Explorer and a word processor like MS Word then you already have the basic skills you need to find your way aroun...",""],
["./hm_quickstart_explorer_sections.htm","Using the Project Explorer &#62; Project Explorer Sections","When you load a project its contents and settings are accessible in three main sections in the Project Explorer on the left: Table of Contents, Pr...",""],
["./hm_quickstart_graphics.htm","Welcome to Help+Manual! &#62; Inserting graphics","In addition to text you will also want to add graphics to illustrate your topics. This tutorial shows you how to add ordinary graphic images to yo...",""],
["./hm_quickstart_links.htm","Welcome to Help+Manual! &#62; Creating hyperlinks","The Web without hyperlinks would be unthinkable and the same applies to interactive help and documentation. Hyperlinks between topics are what mak...",""],
["./hm_quickstart_newproject.htm","Welcome to Help+Manual! &#62; Creating projects","local local You can create a new Help+Manual project from scratch or import documentation from another source and convert it into a new Help+Manua...",""],
["./hm_quickstart_orgtoc.htm","Welcome to Help+Manual! &#62; Organizing the TOC","One of the main differences between Help+Manual and a word processor is that in a word processor you work in a single document. In contrast to thi...",""],
["./hm_quickstart_styles.htm","Welcome to Help+Manual! &#62; Using styles","You can format all your text manually if you like but it&#39;s much more efficient to use styles. Styles are formatting definitions that you can apply...",""],
["./hm_quickstart_tables.htm","Welcome to Help+Manual! &#62; Inserting Tables","Tables can be used both to arrange tabular data and as a formatting tool, in the same way as in HTML pages. However, in preparation for responsive...",""],
["./hm_tutorials_other.htm","Welcome to Help+Manual! &#62; Template files","In addition to the other resources listed in this chapter the \\Templates folder in the Help+Manual program directory also contains a number of oth...",""]];
